In [3]:
import pandas as pd

feature selection advance home_price prediction

In [4]:
home_data=pd.read_csv("X_train.csv")

In [5]:
home_data.head()

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,12.247694,0.235294,0.75,0.0,0.366344,1.0,1.0,0.000000,0.333333,...,0.0,0.0,0.0,1.0,1.0,0.0,0.090909,0.50,0.666667,0.75
1,2,12.109011,0.000000,0.75,0.0,0.391317,1.0,1.0,0.000000,0.333333,...,0.0,0.0,0.0,1.0,1.0,0.0,0.363636,0.25,0.666667,0.75
2,3,12.317167,0.235294,0.75,0.0,0.422359,1.0,1.0,0.333333,0.333333,...,0.0,0.0,0.0,1.0,1.0,0.0,0.727273,0.50,0.666667,0.75
3,4,11.849398,0.294118,0.75,0.0,0.390295,1.0,1.0,0.333333,0.333333,...,0.0,0.0,0.0,1.0,1.0,0.0,0.090909,0.00,0.666667,0.00
4,5,12.429216,0.235294,0.75,0.0,0.468761,1.0,1.0,0.333333,0.333333,...,0.0,0.0,0.0,1.0,1.0,0.0,1.000000,0.50,0.666667,0.75

In [6]:
#capture dependent feature

In [7]:
y_train=home_data[['SalePrice']]

In [8]:
y_train

      SalePrice
0     12.247694
1     12.109011
2     12.317167
3     11.849398
4     12.429216
...         ...
1455  12.072541
1456  12.254863
1457  12.493130
1458  11.864462
1459  11.901583

[1460 rows x 1 columns]

In [9]:
X_train=home_data.drop(['SalePrice','Id'],axis=1)

In [10]:
X_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.235294,0.75,0.0,0.366344,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.090909,0.50,0.666667,0.75
1,0.000000,0.75,0.0,0.391317,1.0,1.0,0.000000,0.333333,1.0,0.50,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.363636,0.25,0.666667,0.75
2,0.235294,0.75,0.0,0.422359,1.0,1.0,0.333333,0.333333,1.0,0.00,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.727273,0.50,0.666667,0.75
3,0.294118,0.75,0.0,0.390295,1.0,1.0,0.333333,0.333333,1.0,0.25,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.090909,0.00,0.666667,0.00
4,0.235294,0.75,0.0,0.468761,1.0,1.0,0.333333,0.333333,1.0,0.50,...,0.0,0.0,0.0,1.00,1.0,0.00000,1.000000,0.50,0.666667,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.75,0.0,0.353592,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.636364,0.25,0.666667,0.75
1456,0.000000,0.75,0.0,0.453273,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,0.50,1.0,0.00000,0.090909,1.00,0.666667,0.75
1457,0.294118,0.75,0.0,0.379597,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,0.75,0.5,0.16129,0.363636,1.00,0.666667,0.75
1458,0.000000,0.75,0.0,0.393688,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.272727,1.00,0.666667,0.75
1459,0.000000,0.75,0.0,0.398069,1.0,1.0,0.000000,0.333333,1.0,0.00,...,0.0,0.0,0.0,1.00,1.0,0.00000,0.454545,0.50,0.666667,0.75

Apply feature selection

1.first i specify the lasso regression model and 

2.select a suitable alpha

3.bigger the alpha the less feature that will be selected

4.then i selected model

5.will select the feature which coefficients are non-zero

In [11]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
feature_sel_model=SelectFromModel(Lasso(alpha=0.005,random_state=0))
feature_sel_model.fit(X_train.fillna(0),y_train)

SelectFromModel(estimator=Lasso(alpha=0.005, random_state=0))

In [12]:
feature_sel_model.get_support()

array([ True,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True, False, False, False, False, False,  True, False,
       False,  True,  True,  True, False,  True,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True])

1.let is print the number of total and selected feature

2.this is how we can make a list of the selected feature

In [13]:
import numpy as np
selected_feature=X_train.columns[(feature_sel_model.get_support())]
print("Total feature :{}".format((X_train.shape[1])))
print("Selected Features dataset :{}".format(len(selected_feature)))

Total feature :79
Selected Features dataset :21

In [14]:
selected_feature

Index(['MSSubClass', 'MSZoning', 'Neighborhood', 'OverallQual', 'YearRemodAdd',
       'RoofStyle', 'BsmtQual', 'BsmtExposure', 'HeatingQC', 'CentralAir',
       '1stFlrSF', 'GrLivArea', 'BsmtFullBath', 'KitchenQual', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageCars', 'PavedDrive',
       'SaleCondition'],
      dtype='object')

In [15]:
X_train=X_train[selected_feature]

In [16]:
X_train

,MSSubClass,MSZoning,Neighborhood,OverallQual,YearRemodAdd,RoofStyle,BsmtQual,BsmtExposure,HeatingQC,CentralAir,...,GrLivArea,BsmtFullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition
0,0.235294,0.75,0.636364,0.666667,0.098361,0.0,0.75,0.25,1.00,1.0,...,0.577712,0.333333,0.666667,0.000000,0.2,0.8,0.666667,0.50,1.0,0.75
1,0.000000,0.75,0.500000,0.555556,0.524590,0.0,0.75,1.00,1.00,1.0,...,0.470245,0.000000,0.333333,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75
2,0.235294,0.75,0.636364,0.666667,0.114754,0.0,0.75,0.50,1.00,1.0,...,0.593095,0.333333,0.666667,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75
3,0.294118,0.75,0.727273,0.666667,0.606557,0.0,0.50,0.25,0.75,1.0,...,0.579157,0.333333,0.666667,0.333333,0.8,0.4,0.333333,0.75,1.0,0.00
4,0.235294,0.75,1.000000,0.777778,0.147541,0.0,0.75,0.75,1.00,1.0,...,0.666523,0.333333,0.666667,0.333333,0.6,0.8,0.666667,0.75,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.75,0.590909,0.555556,0.131148,0.0,0.75,0.25,1.00,1.0,...,0.564433,0.000000,0.333333,0.333333,0.6,0.8,0.666667,0.50,1.0,0.75
1456,0.000000,0.75,0.545455,0.555556,0.377049,0.0,0.75,0.25,0.50,1.0,...,0.645810,0.333333,0.333333,0.666667,0.6,0.8,0.333333,0.50,1.0,0.75
1457,0.294118,0.75,0.727273,0.666667,0.081967,0.0,0.50,0.25,1.00,1.0,...,0.688669,0.000000,0.666667,0.666667,0.8,0.8,0.666667,0.25,1.0,0.75
1458,0.000000,0.75,0.363636,0.444444,0.245902,1.0,0.50,0.50,0.75,1.0,...,0.414497,0.333333,0.666667,0.000000,0.2,0.8,0.333333,0.25,1.0,0.75
1459,0.000000,0.75,0.227273,0.444444,0.721311,0.0,0.50,0.25,0.75,1.0,...,0.468559,0.333333,0.333333,0.000000,0.2,0.8,1.000000,0.25,1.0,0.75